'use client';

import { useMemo, useState, useTransition } from 'react';
import { Edit, KeyRound, Mail, Phone, Plus } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { saveRenterAction, setRenterPortalPasswordAction } from '@/actions/renters';
import { Drawer, EmptyState, FormSection, WorkspaceToolbar } from '@/components/ui/workspace';
import { WorkspaceSearch } from '@/components/ui/workspace-search';

interface RenterItem {
  id:string;firstName:string;lastName:string;fullName:string;dni:string;email?:string|null;phone?:string|null;address?:string|null;status:string;hasPortalAccess:boolean;notes?:string|null;
  activePropertyLeases:Array<{id:string;propertyCode:string;rent:number}>;activeGarageLeasesCount:number;totalPendingDebt:number;
}

export function RentersClient({ initialRenters }: { initialRenters: RenterItem[] }) {
  const [search,setSearch]=useState(''); const [isPending,startTransition]=useTransition(); const [editingRenter,setEditingRenter]=useState<RenterItem|null>(null); const [isRenterDrawerOpen,setIsRenterDrawerOpen]=useState(false); const [portalModalRenter,setPortalModalRenter]=useState<RenterItem|null>(null); const [portalPassword,setPortalPassword]=useState(''); const [portalSuccess,setPortalSuccess]=useState(false); const [error,setError]=useState('');
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return initialRenters.filter(r=>!q||r.fullName.toLowerCase().includes(q)||r.dni.includes(q)||(r.email||'').toLowerCase().includes(q))},[initialRenters,search]);
  const debtors=initialRenters.filter(r=>r.totalPendingDebt>0).length;
  function openRenter(renter?:RenterItem){setEditingRenter(renter||null);setError('');setIsRenterDrawerOpen(true)}
  function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');startTransition(async()=>{try{await saveRenterAction({id:editingRenter?.id,firstName:String(f.get('firstName')||''),lastName:String(f.get('lastName')||''),dni:String(f.get('dni')||''),email:String(f.get('email')||''),phone:String(f.get('phone')||''),address:String(f.get('address')||''),status:String(f.get('status')||'ACTIVE') as any,notes:String(f.get('notes')||'')});setIsRenterDrawerOpen(false);window.location.reload()}catch(err:any){setError(err?.message||'No se pudo guardar el inquilino.')}})}
  function setPassword(e:React.FormEvent){e.preventDefault();if(!portalModalRenter)return;startTransition(async()=>{await setRenterPortalPasswordAction(portalModalRenter.id,portalPassword);setPortalSuccess(true);setTimeout(()=>{setPortalSuccess(false);setPortalModalRenter(null);setPortalPassword('');window.location.reload()},800)})}
  return <div className="space-y-5">
    <div className="ui-summary-strip"><span className="ui-summary-chip"><strong>{initialRenters.length}</strong> inquilinos</span><span className="ui-summary-chip"><strong>{initialRenters.filter(r=>r.status==='ACTIVE').length}</strong> activos</span><span className="ui-summary-chip"><strong>{debtors}</strong> con saldo</span><span className="ui-summary-chip"><strong>{initialRenters.filter(r=>r.hasPortalAccess).length}</strong> con portal</span></div>
    <WorkspaceToolbar><div className="ui-filter-row"><WorkspaceSearch value={search} onChange={setSearch} placeholder="Buscar por nombre, DNI o email..."/></div><button type="button" onClick={()=>openRenter()} className="btn-primary"><Plus className="w-4 h-4"/>Nuevo inquilino</button></WorkspaceToolbar>
    <section className="ui-list-shell">{filtered.length===0?<EmptyState title="No hay inquilinos para mostrar"/>:filtered.map(r=><div key={r.id} className="ui-list-row"><div><div className="flex items-center gap-2"><div className="ui-list-row__title">{r.fullName}</div><span className={`status-pill ${r.status==='ACTIVE'?'status-pill--success':'status-pill--neutral'}`}>{r.status==='ACTIVE'?'Activo':'Inactivo'}</span></div><div className="ui-list-row__meta">DNI {r.dni}{r.phone?` · ${r.phone}`:''}{r.email?` · ${r.email}`:''}</div></div><div><div className="text-[9px] text-slate-400">Contratos</div><div className="text-xs font-bold">{r.activePropertyLeases.length+r.activeGarageLeasesCount}</div></div><div><div className="text-[9px] text-slate-400">Saldo</div><div className={`text-xs font-bold ${r.totalPendingDebt>0?'text-rose-600':'text-emerald-600'}`}>{formatCurrency(r.totalPendingDebt)}</div></div><div className="ui-actions"><button type="button" onClick={()=>{setPortalModalRenter(r);setPortalPassword('')}} className="ui-action-secondary"><KeyRound className="w-3.5 h-3.5"/>{r.hasPortalAccess?'Clave portal':'Activar portal'}</button><button type="button" onClick={()=>openRenter(r)} className="icon-action" title="Editar"><Edit className="w-4 h-4"/></button></div></div>)}</section>

    <Drawer open={isRenterDrawerOpen} onClose={()=>setIsRenterDrawerOpen(false)} title={editingRenter?'Editar inquilino':'Nuevo inquilino'} subtitle="Datos personales y de contacto separados de la operatoria contractual." width="wide">
      <form onSubmit={save}>{error&&<div className="mb-4 p-3 bg-rose-50 border border-rose-100 rounded-lg text-sm text-rose-700">{error}</div>}<FormSection title="Identidad"><Field name="firstName" label="Nombre *" required defaultValue={editingRenter?.firstName||''}/><Field name="lastName" label="Apellido *" required defaultValue={editingRenter?.lastName||''}/><Field name="dni" label="DNI / Documento *" required defaultValue={editingRenter?.dni||''}/><Select name="status" label="Estado" defaultValue={editingRenter?.status||'ACTIVE'} options={[["ACTIVE","Activo"],["INACTIVE","Inactivo"]]}/></FormSection><FormSection title="Contacto"><Field name="email" label="Correo electrónico" type="email" defaultValue={editingRenter?.email||''}/><Field name="phone" label="Teléfono / WhatsApp" defaultValue={editingRenter?.phone||''}/><Field name="address" label="Domicilio" defaultValue={editingRenter?.address||''}/><label><span className="form-label">Notas</span><textarea name="notes" rows={4} defaultValue={editingRenter?.notes||''} className="form-input"/></label></FormSection><div className="ui-form-actions"><button type="button" onClick={()=>setIsRenterDrawerOpen(false)} className="btn-secondary">Cancelar</button><button disabled={isPending} className="btn-primary">{isPending?'Guardando...':'Guardar inquilino'}</button></div></form>
    </Drawer>

    <Drawer open={!!portalModalRenter} onClose={()=>setPortalModalRenter(null)} title="Acceso al portal" subtitle={portalModalRenter?`${portalModalRenter.fullName} · DNI ${portalModalRenter.dni}`:''}>
      {portalModalRenter&&<form onSubmit={setPassword}><FormSection title="Credencial" description="Definí una nueva clave de acceso para el portal del inquilino."><div className="col-span-full"><label className="form-label">Nueva contraseña</label><input type="password" required minLength={8} value={portalPassword} onChange={e=>setPortalPassword(e.target.value)} className="form-input" placeholder="Mínimo 8 caracteres"/></div>{portalSuccess&&<div className="col-span-full p-3 bg-emerald-50 border border-emerald-100 rounded-lg text-sm text-emerald-700">Acceso actualizado correctamente.</div>}</FormSection><div className="ui-form-actions"><button type="button" onClick={()=>setPortalModalRenter(null)} className="btn-secondary">Cancelar</button><button disabled={isPending} className="btn-primary"><KeyRound className="w-4 h-4"/>Guardar acceso</button></div></form>}
    </Drawer>
  </div>
}
function Field({name,label,type='text',required,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string}){return <label><span className="form-label">{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue} className="form-input"/></label>}
function Select({name,label,defaultValue,options}:{name:string;label:string;defaultValue:string;options:Array<[string,string]>}){return <label><span className="form-label">{label}</span><select name={name} defaultValue={defaultValue} className="form-input">{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
