import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft,Banknote,Building2,CalendarClock,FileText,Wrench } from 'lucide-react';
import { getLease360Action } from '@/actions/lease-360';
import { DataTable,DetailGrid,EntityHero,MetricCard,SectionCard,StatusPill,Timeline } from '@/components/entity-360/entity-360-ui';
import { adjustmentDisplayLabel, adjustmentMethodLabel } from '@/lib/lease-labels';

export const dynamic='force-dynamic';
const money=(v:any)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(Number(v||0));
const date=(v:any)=>v?new Intl.DateTimeFormat('es-AR').format(new Date(v)):'—';
const name=(p:any)=>p?(p.companyName||`${p.firstName||''} ${p.lastName||''}`.trim()||'—'):'—';
function tone(s?:string):'neutral'|'success'|'warning'|'danger'|'info'{if(!s)return'neutral';if(['CURRENT','PAID','SIGNED','RESOLVED','COMPLETED'].includes(s))return'success';if(['OVERDUE','CANCELED','TERMINATED','FAILED'].includes(s))return'danger';if(['EXPIRING','PENDING','PARTIAL','URGENT'].includes(s))return'warning';return'info'}

export default async function Lease360Page({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const data:any=await getLease360Action(id);if(!data)notFound();const l=data.lease;const debts=l.debts||[];const payments=debts.flatMap((d:any)=>d.payments||[]);const pending=debts.reduce((s:number,d:any)=>s+Math.max(0,Number(d.amount)-Number(d.paidAmount)),0);const paid=payments.reduce((s:number,p:any)=>s+Number(p.amount||0),0);const openMaintenance=data.maintenance.filter((m:any)=>!['RESOLVED','CANCELED'].includes(m.status));const adjustmentLabel=adjustmentDisplayLabel(l.adjustmentIndex,l.adjustmentMethod);
 return <div className="app-page"><div className="page-container space-y-6">
  <Link href="/contratos" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="w-4 h-4"/> Contratos</Link>
  <EntityHero eyebrow="Contrato 360" title={`${l.property.code} · ${l.property.address}`} subtitle={`${l.renter.firstName} ${l.renter.lastName} · ${date(l.startDate)} → ${date(l.endDate)}`} badges={[{label:l.status,tone:tone(l.status)},{label:adjustmentLabel,tone:'info'},{label:l.guaranteeType||'Sin garantía',tone:'neutral'}]} actions={<Link href={`/propiedades/${l.propertyId}`} className="btn-primary"><Building2 className="w-4 h-4"/> Propiedad 360</Link>} media={<div className="entity-hero__placeholder"><FileText className="w-12 h-12"/><span>Contrato</span></div>}/>
  <nav className="entity-subnav">{[['resumen','Resumen'],['cuenta','Cuenta corriente'],['ajustes','Ajustes'],['garantias','Garantías'],['mantenimiento','Mantenimiento'],['documentos','Documentos'],['actividad','Actividad']].map(([h,lbl])=><a key={h} href={`#${h}`} className="entity-subnav__link">{lbl}</a>)}</nav>
  <section id="resumen" className="scroll-mt-28 space-y-5"><div className="grid grid-cols-2 xl:grid-cols-5 gap-3"><MetricCard label="Alquiler actual" value={money(l.currentRent)} detail={`Inicial ${money(l.initialRent)}`} icon={<Banknote className="w-5 h-5"/>}/><MetricCard label="Saldo pendiente" value={money(pending)} detail={`${debts.filter((d:any)=>d.status!=='PAID').length} cargos`} icon={<CalendarClock className="w-5 h-5"/>}/><MetricCard label="Cobrado" value={money(paid)} detail={`${payments.length} pagos`} icon={<Banknote className="w-5 h-5"/>}/><MetricCard label="Próximo ajuste" value={date(l.nextAdjustmentDate)} detail={adjustmentLabel} icon={<CalendarClock className="w-5 h-5"/>}/><MetricCard label="Mantenimiento abierto" value={openMaintenance.length} detail={`${data.maintenance.length} histórico`} icon={<Wrench className="w-5 h-5"/>}/></div>
   <div className="grid xl:grid-cols-3 gap-5"><SectionCard title="Contrato" subtitle="Condiciones principales"><DetailGrid items={[{label:'Estado',value:l.status},{label:'Inicio',value:date(l.startDate)},{label:'Fin',value:date(l.endDate)},{label:'Prórroga',value:date(l.extensionUntil)},{label:'Depósito',value:money(l.deposit)},{label:'Método ajuste',value:adjustmentMethodLabel(l.adjustmentMethod)},{label:'Índice',value:l.adjustmentIndex||'—'},{label:'Renovación',value:l.renewalReference||'—'}]}/></SectionCard><SectionCard title="Inquilino" subtitle="Parte locataria"><DetailGrid items={[{label:'Nombre',value:`${l.renter.firstName} ${l.renter.lastName}`},{label:'DNI',value:l.renter.dni},{label:'Email',value:l.renter.email||'—'},{label:'Teléfono',value:l.renter.phone||'—'},{label:'Domicilio',value:l.renter.address||'—'}]}/></SectionCard><SectionCard title="Propiedad / propietarios" subtitle="Activo administrado"><Link href={`/propiedades/${l.propertyId}`} className="block font-bold text-indigo-600 mb-3">{l.property.code} · {l.property.address}</Link><div className="space-y-2">{l.property.owners.map((o:any)=><Link key={o.id} href={`/contactos/${o.contactId}`} className="flex justify-between rounded-xl border p-3"><span className="text-sm font-semibold">{name(o.contact)}</span><span className="font-mono text-xs">{Number(o.ownershipPercentage).toFixed(2)}%</span></Link>)}</div></SectionCard></div>
  </section>
  <SectionCard id="cuenta" title="Cuenta corriente" subtitle="Cargos, pagos y conciliación"><DataTable headers={['Concepto','Vence','Total','Pagado','Saldo','Estado']} rows={debts.map((d:any)=>[d.description,date(d.dueDate),money(d.amount),money(d.paidAmount),money(Math.max(0,Number(d.amount)-Number(d.paidAmount))),<StatusPill key="s" tone={tone(d.status)}>{d.status}</StatusPill>])}/><div className="mt-5"><DataTable headers={['Fecha','Cuenta','Movimiento','Importe','Conciliación']} rows={data.financial.map((m:any)=>[date(m.occurredAt),m.accountName,m.concept,money(m.amount),<StatusPill key="s" tone={tone(m.reconciliationStatus)}>{m.reconciliationStatus}</StatusPill>])}/></div></SectionCard>
  <SectionCard id="ajustes" title="Historial de ajustes" subtitle="Evolución del alquiler"><DataTable headers={['Fecha','Anterior','Nuevo','Método','Variación']} rows={l.rentHistory.map((h:any)=>[date(h.changeDate),money(h.previousRent),money(h.newRent),adjustmentMethodLabel(h.method)||'—',h.percentage?`${Number(h.percentage).toFixed(2)}%`:'—'])}/></SectionCard>
  <SectionCard id="garantias" title="Garantía, garante e inventario" subtitle="Información contractual de respaldo"><div className="grid xl:grid-cols-2 gap-5"><DetailGrid items={[{label:'Tipo',value:l.guaranteeType||'—'},{label:'Garante',value:name(l.guarantor)},{label:'Detalle',value:l.guaranteeDetails||'—'},{label:'Depósito',value:money(l.deposit)}]}/><DetailGrid items={[{label:'Checklist ingreso',value:l.entryChecklist||'—'},{label:'Checklist egreso',value:l.exitChecklist||'—'},{label:'Inventario',value:l.inventoryNotes||'—'},{label:'Notas',value:l.notes||'—'}]}/></div></SectionCard>
  <SectionCard id="mantenimiento" title="Mantenimiento e inspecciones" subtitle="Incidencias ocurridas durante el contrato"><div className="grid xl:grid-cols-2 gap-5"><DataTable headers={['Trabajo','Proveedor','Costo','Estado']} rows={data.maintenance.map((m:any)=>[m.title,name(m.provider),money(m.actualCost||m.approvedAmount||m.quotedAmount||0),<StatusPill key="s" tone={tone(m.status)}>{m.status}</StatusPill>])}/><DataTable headers={['Inspección','Fecha','Hallazgos','Estado']} rows={data.inspections.map((i:any)=>[i.type,date(i.performedAt||i.scheduledAt),i.findings.length,<StatusPill key="s" tone={tone(i.status)}>{i.status}</StatusPill>])}/></div></SectionCard>
  <SectionCard id="documentos" title="Documentos" subtitle="Documentación contractual"><DataTable headers={['Archivo','Categoría','Fecha','Acción']} rows={l.documents.map((d:any)=>[d.fileName,d.category,date(d.uploadedAt),<a key="o" href={d.fileUrl} target="_blank" rel="noreferrer" className="font-semibold text-indigo-600">Abrir</a>])}/></SectionCard>
  <SectionCard id="actividad" title="Actividad 360" subtitle="Timeline de contrato, propiedad e inquilino"><Timeline items={data.activity.map((e:any)=>({id:e.id,title:e.title,detail:e.description,date:e.createdAt,actor:e.actorName}))}/></SectionCard>
 </div></div>
}
