'use client';

import { useMemo, useState, useTransition } from 'react';
import { ClipboardCheck, HardHat, Plus, SearchCheck, ShieldCheck, Wrench } from 'lucide-react';
import {
  addInspectionFindingAction,
  createMaintenanceFromFindingAction,
  saveInspectionAction,
  saveMaintenanceRequestAction,
  saveProviderProfileAction,
  setMaintenanceStatusAction,
} from '@/actions/maintenance';
import { Drawer, EmptyState, FormSection, WorkspaceMetric, WorkspaceMetrics, WorkspaceTab, WorkspaceTabs, WorkspaceToolbar } from '@/components/ui/workspace';

type Tab = 'ORDERS' | 'PROVIDERS' | 'INSPECTIONS';

export function MaintenanceClient({ data }: { data: any }) {
  const [tab,setTab]=useState<Tab>('ORDERS');
  const [showForm,setShowForm]=useState(false);
  const [findingInspectionId,setFindingInspectionId]=useState<string|null>(null);
  const [selectedInspection,setSelectedInspection]=useState<any|null>(null);
  const [error,setError]=useState('');
  const [isPending,startTransition]=useTransition();
  const providers=useMemo(()=>data.providers||[],[data.providers]);
  const openOrders=data.requests.filter((r:any)=>!['RESOLVED','CANCELED'].includes(r.status)).length;
  const urgentOrders=data.requests.filter((r:any)=>r.priority==='URGENT'&&!['RESOLVED','CANCELED'].includes(r.status)).length;
  const unresolvedFindings=data.inspections.flatMap((i:any)=>i.findings).filter((f:any)=>!f.resolved).length;

  function run(task:()=>Promise<any>,reload=true){setError('');startTransition(async()=>{try{await task();if(reload)window.location.reload()}catch(err:any){setError(err?.message||'No se pudo completar la operación.')}})}
  function submitOrder(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);run(()=>saveMaintenanceRequestAction({propertyId:String(form.get('propertyId')||''),propertyLeaseId:String(form.get('propertyLeaseId')||'')||null,renterId:String(form.get('renterId')||'')||null,providerContactId:String(form.get('providerContactId')||'')||null,assignedUserId:String(form.get('assignedUserId')||'')||null,category:String(form.get('category')||''),priority:String(form.get('priority')||'NORMAL') as any,title:String(form.get('title')||''),description:String(form.get('description')||''),reportedBy:String(form.get('reportedBy')||'')||null,quotedAmount:form.get('quotedAmount')?Number(form.get('quotedAmount')):null,approvedAmount:form.get('approvedAmount')?Number(form.get('approvedAmount')):null,actualCost:form.get('actualCost')?Number(form.get('actualCost')):null,costBearer:String(form.get('costBearer')||'UNASSIGNED') as any,ownerApproved:form.get('ownerApproved')==='on',scheduledAt:String(form.get('scheduledAt')||'')||null,promisedAt:String(form.get('promisedAt')||'')||null}))}
  function submitProvider(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const specialties=String(form.get('specialties')||'').split(',').map(v=>v.trim()).filter(Boolean);run(()=>saveProviderProfileAction({contactId:String(form.get('contactId')||''),specialties,rating:form.get('rating')?Number(form.get('rating')):null,insuranceInfo:String(form.get('insuranceInfo')||'')||null,notes:String(form.get('notes')||'')||null,isActive:true}))}
  function submitInspection(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const checklist=String(form.get('checklist')||'').split('\n').map(v=>v.trim()).filter(Boolean);run(()=>saveInspectionAction({propertyId:String(form.get('propertyId')||''),propertyLeaseId:String(form.get('propertyLeaseId')||'')||null,renterId:String(form.get('renterId')||'')||null,inspectorUserId:String(form.get('inspectorUserId')||'')||null,type:String(form.get('type')||'PERIODIC') as any,status:String(form.get('status')||'SCHEDULED') as any,scheduledAt:String(form.get('scheduledAt')||'')||null,performedAt:String(form.get('performedAt')||'')||null,checklist,summary:String(form.get('summary')||'')||null}))}
  function submitFinding(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(!findingInspectionId)return;run(()=>addInspectionFindingAction({inspectionId:findingInspectionId,severity:String(form.get('severity')||'MEDIUM') as any,area:String(form.get('area')||'')||null,description:String(form.get('description')||''),photos:[]}))}
  function newItem(){setShowForm(true);setError('')}

  return <div className="space-y-5">
    <WorkspaceMetrics>
      <WorkspaceMetric icon={<Wrench className="w-5 h-5"/>} label="Órdenes abiertas" value={openOrders}/>
      <WorkspaceMetric icon={<HardHat className="w-5 h-5"/>} label="Urgentes" value={urgentOrders}/>
      <WorkspaceMetric icon={<SearchCheck className="w-5 h-5"/>} label="Hallazgos pendientes" value={unresolvedFindings}/>
    </WorkspaceMetrics>

    <WorkspaceToolbar>
      <WorkspaceTabs>
        <WorkspaceTab active={tab==='ORDERS'} onClick={()=>{setTab('ORDERS');setShowForm(false)}}>Órdenes</WorkspaceTab>
        <WorkspaceTab active={tab==='PROVIDERS'} onClick={()=>{setTab('PROVIDERS');setShowForm(false)}}>Proveedores</WorkspaceTab>
        <WorkspaceTab active={tab==='INSPECTIONS'} onClick={()=>{setTab('INSPECTIONS');setShowForm(false)}}>Inspecciones</WorkspaceTab>
      </WorkspaceTabs>
      <button type="button" onClick={newItem} className="btn-primary"><Plus className="w-4 h-4"/>{tab==='ORDERS'?'Nueva orden':tab==='PROVIDERS'?'Nuevo perfil':'Nueva inspección'}</button>
    </WorkspaceToolbar>

    {error&&!showForm&&<div className="p-3 bg-rose-50 border border-rose-100 rounded-lg text-sm text-rose-700">{error}</div>}

    {tab==='ORDERS'&&<section className="ui-list-shell">{data.requests.length===0?<EmptyState title="Todavía no hay órdenes de mantenimiento"/>:data.requests.map((request:any)=><div key={request.id} className="ui-list-row"><div><div className="flex flex-wrap items-center gap-2"><div className="ui-list-row__title">{request.title}</div><Status value={request.status}/><Priority value={request.priority}/></div><div className="ui-list-row__meta">{request.property.code} · {request.property.address} · {request.category}</div></div><div><div className="text-[9px] text-slate-400">Proveedor</div><div className="text-xs font-semibold">{request.provider?providerName(request.provider):'Sin asignar'}</div></div><div><div className="text-[9px] text-slate-400">Costo</div><div className="text-xs font-bold">{money(request.actualCost??request.approvedAmount??request.quotedAmount)}</div></div><div className="ui-actions">{request.status==='OPEN'&&<Small onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'TRIAGED'))}>Clasificar</Small>}{request.status==='TRIAGED'&&<Small onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'QUOTED'))}>Presupuestar</Small>}{['TRIAGED','QUOTED'].includes(request.status)&&<Small onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'APPROVED'))}>Aprobar</Small>}{['APPROVED','WAITING_PARTS'].includes(request.status)&&<Small primary onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'IN_PROGRESS'))}>Iniciar</Small>}{request.status==='IN_PROGRESS'&&<Small onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'WAITING_PARTS'))}>Espera repuesto</Small>}{['APPROVED','IN_PROGRESS','WAITING_PARTS'].includes(request.status)&&<Small primary onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'RESOLVED'))}>Resolver</Small>}{!['RESOLVED','CANCELED'].includes(request.status)&&<Small danger onClick={()=>run(()=>setMaintenanceStatusAction(request.id,'CANCELED'))}>Cancelar</Small>}</div></div>)}</section>}

    {tab==='PROVIDERS'&&<section className="ui-list-shell">{providers.length===0?<EmptyState title="Todavía no hay contactos con rol Proveedor"/>:providers.map((provider:any)=><div key={provider.id} className="ui-list-row"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><ShieldCheck className="w-4 h-4"/></div><div><div className="ui-list-row__title">{providerName(provider)}</div><div className="ui-list-row__meta">{provider.phone||'Sin teléfono'} · {provider.email||'Sin email'}</div></div></div><div><div className="text-[9px] text-slate-400">Rubros</div><div className="text-xs font-semibold">{Array.isArray(provider.providerProfile?.specialties)&&provider.providerProfile.specialties.length?provider.providerProfile.specialties.join(' · '):'Sin definir'}</div></div><div><div className="text-[9px] text-slate-400">Valoración</div><div className="text-xs font-bold">{provider.providerProfile?.rating??'—'}/5</div></div><div className="text-[10px] text-slate-500">{provider.providerProfile?.insuranceInfo||'Sin matrícula/seguro'}</div></div>)}</section>}

    {tab==='INSPECTIONS'&&<section className="ui-list-shell">{data.inspections.length===0?<EmptyState title="Todavía no hay inspecciones"/>:data.inspections.map((inspection:any)=><div key={inspection.id} className="ui-list-row"><div><div className="flex items-center gap-2"><ClipboardCheck className="w-4 h-4 text-indigo-600"/><div className="ui-list-row__title">{inspection.type} · {inspection.property.code}</div><Status value={inspection.status}/></div><div className="ui-list-row__meta">{inspection.property.address} · {inspection.inspector?.name||'Sin inspector'}</div></div><div><div className="text-[9px] text-slate-400">Hallazgos</div><div className="text-xs font-bold">{inspection.findings.length}</div></div><div><div className="text-[9px] text-slate-400">Pendientes</div><div className="text-xs font-bold text-amber-600">{inspection.findings.filter((f:any)=>!f.resolved).length}</div></div><div className="ui-actions"><button type="button" onClick={()=>setSelectedInspection(inspection)} className="ui-action-secondary">Ver detalle</button><button type="button" onClick={()=>{setFindingInspectionId(inspection.id);setSelectedInspection(inspection)}} className="btn-primary">Hallazgo</button></div></div>)}</section>}

    <Drawer open={showForm} onClose={()=>setShowForm(false)} title={tab==='ORDERS'?'Nueva orden de mantenimiento':tab==='PROVIDERS'?'Completar perfil de proveedor':'Nueva inspección'} subtitle="La carga se realiza fuera del listado para mantener el módulo limpio y operativo." width="wide">
      {error&&<div className="mb-4 p-3 bg-rose-50 border border-rose-100 rounded-lg text-sm text-rose-700">{error}</div>}
      {tab==='ORDERS'&&<form onSubmit={submitOrder}><FormSection title="Vinculación"><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Select name="propertyLeaseId" label="Contrato" options={[['','Sin contrato'],...data.leases.map((l:any)=>[l.id,`${l.property.code} · ${l.renter.firstName} ${l.renter.lastName}`])]}/><Select name="renterId" label="Inquilino" options={[['','Sin inquilino'],...data.renters.map((r:any)=>[r.id,`${r.firstName} ${r.lastName}`])]}/><Select name="providerContactId" label="Proveedor" options={[['','Sin asignar'],...providers.map((p:any)=>[p.id,providerName(p)])]}/></FormSection><FormSection title="Clasificación"><Field name="category" label="Categoría *" placeholder="Plomería, electricidad..."/><Select name="priority" label="Prioridad" options={[["LOW","Baja"],["NORMAL","Normal"],["HIGH","Alta"],["URGENT","Urgente"]]}/><Select name="assignedUserId" label="Responsable interno" options={[['','Sin asignar'],...data.users.map((u:any)=>[u.id,u.name])]}/><Select name="costBearer" label="Quién absorbe el costo" options={[["UNASSIGNED","Sin definir"],["OWNER","Propietario"],["RENTER","Inquilino"],["TENANT","Inmobiliaria"],["INSURANCE","Seguro"]]}/><Field name="title" label="Título *"/><Field name="reportedBy" label="Reportado por"/></FormSection><FormSection title="Detalle y costos"><div className="col-span-full"><TextArea name="description" label="Descripción *" rows={4}/></div><Field name="quotedAmount" label="Presupuesto" type="number"/><Field name="approvedAmount" label="Importe aprobado" type="number"/><Field name="actualCost" label="Costo real" type="number"/><Field name="scheduledAt" label="Programado" type="datetime-local"/><Field name="promisedAt" label="Fecha prometida" type="datetime-local"/><label className="flex items-center gap-2 text-xs text-slate-600"><input name="ownerApproved" type="checkbox"/>Aprobado por propietario</label></FormSection><Actions close={()=>setShowForm(false)} pending={isPending} label="Crear orden"/></form>}
      {tab==='PROVIDERS'&&<form onSubmit={submitProvider}><FormSection title="Perfil operativo"><Select name="contactId" label="Contacto proveedor *" options={providers.map((p:any)=>[p.id,providerName(p)])}/><Field name="specialties" label="Rubros" placeholder="Plomería, gas, pintura"/><Field name="rating" label="Valoración 0 a 5" type="number"/><Field name="insuranceInfo" label="Seguro / matrícula"/><Field name="notes" label="Notas"/></FormSection><Actions close={()=>setShowForm(false)} pending={isPending||providers.length===0} label="Guardar proveedor"/></form>}
      {tab==='INSPECTIONS'&&<form onSubmit={submitInspection}><FormSection title="Vinculación"><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Select name="propertyLeaseId" label="Contrato" options={[['','Sin contrato'],...data.leases.map((l:any)=>[l.id,`${l.property.code} · ${l.renter.firstName} ${l.renter.lastName}`])]}/><Select name="renterId" label="Inquilino" options={[['','Sin inquilino'],...data.renters.map((r:any)=>[r.id,`${r.firstName} ${r.lastName}`])]}/><Select name="inspectorUserId" label="Inspector" options={[['','Sin asignar'],...data.users.map((u:any)=>[u.id,u.name])]}/></FormSection><FormSection title="Inspección"><Select name="type" label="Tipo" options={[["ENTRY","Ingreso"],["EXIT","Egreso"],["PERIODIC","Periódica"],["OTHER","Otra"]]}/><Select name="status" label="Estado" options={[["DRAFT","Borrador"],["SCHEDULED","Programada"],["IN_PROGRESS","En curso"],["COMPLETED","Completada"]]}/><Field name="scheduledAt" label="Programada" type="datetime-local"/><Field name="performedAt" label="Realizada" type="datetime-local"/><TextArea name="checklist" label="Checklist — un punto por línea" rows={5}/><TextArea name="summary" label="Resumen" rows={5}/></FormSection><Actions close={()=>setShowForm(false)} pending={isPending} label="Guardar inspección"/></form>}
    </Drawer>

    <Drawer open={!!selectedInspection} onClose={()=>{setSelectedInspection(null);setFindingInspectionId(null)}} title={selectedInspection?`${selectedInspection.type} · ${selectedInspection.property.code}`:'Inspección'} subtitle={selectedInspection?`${selectedInspection.property.address} · ${selectedInspection.inspector?.name||'Sin inspector'}`:''} width="wide">
      {selectedInspection&&<div className="space-y-5">{selectedInspection.summary&&<section className="rounded-xl bg-slate-50 border border-slate-100 p-4 text-sm text-slate-700">{selectedInspection.summary}</section>}{findingInspectionId===selectedInspection.id&&<form onSubmit={submitFinding}><FormSection title="Registrar hallazgo"><Select name="severity" label="Severidad" options={[["INFO","Informativo"],["LOW","Baja"],["MEDIUM","Media"],["HIGH","Alta"],["CRITICAL","Crítica"]]}/><Field name="area" label="Sector" placeholder="Baño, cocina..."/><div className="col-span-full"><Field name="description" label="Hallazgo *"/></div></FormSection><div className="flex justify-end"><button disabled={isPending} className="btn-primary">Agregar hallazgo</button></div></form>}<section className="section-card"><div className="section-card__header"><div><h3 className="section-card__title">Hallazgos</h3><p className="section-card__subtitle">Observaciones y órdenes derivadas</p></div>{findingInspectionId!==selectedInspection.id&&<button type="button" onClick={()=>setFindingInspectionId(selectedInspection.id)} className="ui-action-secondary">Nuevo hallazgo</button>}</div><div className="section-card__body space-y-2">{selectedInspection.findings.length===0?<EmptyState title="Sin hallazgos registrados"/>:selectedInspection.findings.map((finding:any)=><div key={finding.id} className="rounded-xl border border-slate-100 p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="flex items-center gap-2"><Priority value={finding.severity}/><span className="text-xs font-semibold">{finding.area||'General'}</span></div><p className="text-xs text-slate-700 mt-1">{finding.description}</p>{finding.maintenanceRequest&&<p className="text-[10px] text-indigo-600 mt-1">Orden: {finding.maintenanceRequest.title} · {finding.maintenanceRequest.status}</p>}</div>{!finding.maintenanceRequestId&&<button type="button" onClick={()=>run(()=>createMaintenanceFromFindingAction(finding.id))} className="btn-primary">Crear orden</button>}</div>)}</div></section></div>}
    </Drawer>
  </div>
}

function Actions({close,pending,label}:{close:()=>void;pending:boolean;label:string}){return <div className="ui-form-actions"><button type="button" onClick={close} className="btn-secondary">Cancelar</button><button disabled={pending} className="btn-primary">{label}</button></div>}
function providerName(provider:any){return provider.companyName||`${provider.firstName||''} ${provider.lastName||''}`.trim()||'Proveedor'}
function money(value:number|null|undefined){if(value==null)return'—';return `$ ${new Intl.NumberFormat('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}`}
function Field({name,label,type='text',placeholder}:{name:string;label:string;type?:string;placeholder?:string}){return <label><span className="form-label">{label}</span><input name={name} type={type} placeholder={placeholder} step={type==='number'?'0.01':undefined} className="form-input"/></label>}
function TextArea({name,label,rows=3}:{name:string;label:string;rows?:number}){return <label><span className="form-label">{label}</span><textarea name={name} rows={rows} className="form-input"/></label>}
function Select({name,label,options}:{name:string;label:string;options:any[]}){return <label><span className="form-label">{label}</span><select name={name} className="form-input">{options.map((option:any)=><option key={option[0]} value={option[0]}>{option[1]}</option>)}</select></label>}
function Status({value}:{value:string}){return <span className="status-pill status-pill--neutral">{value}</span>}
function Priority({value}:{value:string}){const urgent=['URGENT','CRITICAL'].includes(value);const high=value==='HIGH';return <span className={`status-pill ${urgent?'status-pill--danger':high?'status-pill--warning':'status-pill--neutral'}`}>{value}</span>}
function Small({children,onClick,primary=false,danger=false}:{children:React.ReactNode;onClick:()=>void;primary?:boolean;danger?:boolean}){return <button type="button" onClick={onClick} className={primary?'btn-primary':danger?'ui-action-secondary ui-action-danger':'ui-action-secondary'}>{children}</button>}
