'use client';

import { useMemo,useState,useTransition } from 'react';
import { ArrowRightLeft, Landmark, Plus, WalletCards } from 'lucide-react';
import { createFinancialAccountAction,createFinancialMovementAction,setFinancialReconciliationAction,transferFinancialAction } from '@/actions/finance';

const money=(v:any,c='ARS')=>new Intl.NumberFormat('es-AR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0));
export function FinanceClient({data}:{data:any}){
 const[showAccount,setShowAccount]=useState(false),[showMovement,setShowMovement]=useState(false),[showTransfer,setShowTransfer]=useState(false),[error,setError]=useState(''),[pending,startTransition]=useTransition();
 const totals=useMemo(()=>({balance:data.accounts.reduce((s:number,a:any)=>s+Number(a.balance||0),0),pending:data.movements.filter((m:any)=>m.reconciliationStatus==='PENDING').length,income:data.movements.filter((m:any)=>m.type==='INCOME').reduce((s:number,m:any)=>s+Number(m.amount||0),0),expense:data.movements.filter((m:any)=>m.type==='EXPENSE').reduce((s:number,m:any)=>s+Number(m.amount||0),0)}),[data]);
 const run=(fn:()=>Promise<any>)=>startTransition(async()=>{try{setError('');await fn();location.reload()}catch(e:any){setError(e?.message||'No se pudo completar la operación.')}});
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-bold">Libro financiero</h2><p className="text-sm text-slate-500">Los pagos registrados se reflejan automáticamente en la cuenta principal.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setShowTransfer(!showTransfer)}><ArrowRightLeft className="w-4 h-4"/> Transferir</button><button className="btn-secondary" onClick={()=>setShowAccount(!showAccount)}><Landmark className="w-4 h-4"/> Nueva cuenta</button><button className="btn-primary" onClick={()=>setShowMovement(!showMovement)}><Plus className="w-4 h-4"/> Movimiento</button></div></div>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><K label="Saldo consolidado" value={money(totals.balance)}/><K label="Ingresos registrados" value={money(totals.income)}/><K label="Egresos registrados" value={money(totals.expense)}/><K label="Sin conciliar" value={totals.pending}/></div>
 {showAccount&&<form className="section-card p-5 grid md:grid-cols-3 gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createFinancialAccountAction({name:String(f.get('name')||''),type:String(f.get('type')||'BANK') as any,currency:String(f.get('currency')||'ARS'),bankName:String(f.get('bankName')||'')||null,alias:String(f.get('alias')||'')||null,cbu:String(f.get('cbu')||'')||null}))}}><Field n="name" l="Nombre"/><Sel n="type" l="Tipo" o={[['BANK','Banco'],['CASH','Caja'],['MERCADO_PAGO','Mercado Pago'],['OTHER','Otra']]}/><Field n="currency" l="Moneda" d="ARS"/><Field n="bankName" l="Banco"/><Field n="alias" l="Alias"/><Field n="cbu" l="CBU/CVU"/><div className="md:col-span-3 flex justify-end"><button disabled={pending} className="btn-primary">Guardar cuenta</button></div></form>}
 {showMovement&&<form className="section-card p-5 grid md:grid-cols-3 gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createFinancialMovementAction({accountId:String(f.get('accountId')||''),type:String(f.get('type')||'INCOME') as any,amount:Number(f.get('amount')||0),currency:String(f.get('currency')||'ARS'),concept:String(f.get('concept')||''),propertyId:String(f.get('propertyId')||'')||null,contactId:String(f.get('contactId')||'')||null,renterId:String(f.get('renterId')||'')||null,reference:String(f.get('reference')||'')||null,notes:String(f.get('notes')||'')||null,occurredAt:String(f.get('occurredAt')||'')||null}))}}><Sel n="accountId" l="Cuenta" o={data.accounts.map((a:any)=>[a.id,a.name])}/><Sel n="type" l="Tipo" o={[['INCOME','Ingreso'],['EXPENSE','Egreso'],['ADJUSTMENT','Ajuste']]}/><Field n="amount" l="Importe" t="number"/><Field n="concept" l="Concepto"/><Sel n="propertyId" l="Propiedad" optional o={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Sel n="contactId" l="Contacto" optional o={data.contacts.map((c:any)=>[c.id,c.companyName||`${c.firstName} ${c.lastName}`])}/><Sel n="renterId" l="Inquilino" optional o={data.renters.map((r:any)=>[r.id,`${r.lastName}, ${r.firstName}`])}/><Field n="reference" l="Referencia"/><Field n="occurredAt" l="Fecha" t="datetime-local"/><div className="md:col-span-3 flex justify-end"><button disabled={pending} className="btn-primary">Registrar movimiento</button></div></form>}
 {showTransfer&&<form className="section-card p-5 grid md:grid-cols-4 gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>transferFinancialAction({fromAccountId:String(f.get('from')||''),toAccountId:String(f.get('to')||''),amount:Number(f.get('amount')||0),concept:String(f.get('concept')||'')}))}}><Sel n="from" l="Desde" o={data.accounts.map((a:any)=>[a.id,a.name])}/><Sel n="to" l="Hacia" o={data.accounts.map((a:any)=>[a.id,a.name])}/><Field n="amount" l="Importe" t="number"/><Field n="concept" l="Concepto"/><div className="md:col-span-4 flex justify-end"><button disabled={pending} className="btn-primary">Transferir</button></div></form>}
 <div className="grid xl:grid-cols-[320px_minmax(0,1fr)] gap-5"><section className="section-card"><div className="section-card__header"><h3 className="section-card__title">Cuentas</h3></div><div className="p-4 space-y-3">{data.accounts.map((a:any)=><div key={a.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold text-sm">{a.name}</p><p className="text-xs text-slate-400">{a.type} · {a.currency}</p></div><p className="font-mono font-bold">{money(a.balance,a.currency)}</p></div></div>)}</div></section><section className="section-card overflow-hidden"><div className="section-card__header"><h3 className="section-card__title">Movimientos</h3></div><div className="table-shell"><table className="data-table"><thead><tr><th>Fecha</th><th>Cuenta</th><th>Concepto</th><th>Vínculo</th><th>Importe</th><th>Conciliación</th></tr></thead><tbody>{data.movements.map((m:any)=><tr key={m.id}><td>{new Date(m.occurredAt).toLocaleDateString('es-AR')}</td><td>{m.accountName}</td><td><b>{m.concept}</b>{m.reference&&<div className="text-[10px] text-slate-400">{m.reference}</div>}</td><td>{m.propertyCode?`${m.propertyCode} · ${m.propertyAddress}`:(m.contactName||m.renterName||'—')}</td><td className={m.type==='EXPENSE'?'text-rose-600 font-mono':'text-emerald-600 font-mono'}>{m.type==='EXPENSE'?'-':'+'}{money(m.amount,m.currency)}</td><td><select value={m.reconciliationStatus} onChange={e=>run(()=>setFinancialReconciliationAction(m.id,e.target.value as any))} className="form-input py-1 text-xs"><option>PENDING</option><option>MATCHED</option><option>IGNORED</option></select></td></tr>)}</tbody></table></div></section></div>
 </div>
}
function K({label,value}:{label:string;value:any}){return <div className="metric-card"><p className="metric-card__label">{label}</p><p className="metric-card__value">{value}</p></div>}
function Field({n,l,t='text',d}:{n:string;l:string;t?:string;d?:string}){return <div><label className="form-label">{l}</label><input name={n} type={t} defaultValue={d} className="form-input"/></div>}
function Sel({n,l,o,optional}:{n:string;l:string;o:any[];optional?:boolean}){return <div><label className="form-label">{l}</label><select name={n} className="form-input">{optional&&<option value="">Sin asignar</option>}{o.map(([v,x])=><option key={v} value={v}>{x}</option>)}</select></div>}
