'use client';

import { useState, useTransition } from 'react';
import { BadgeDollarSign, BookOpenCheck, Plus, RadioTower, ArrowRight, CheckCircle2 } from 'lucide-react';
import { convertReservationToDealAction, saveDealAction, savePublicationAction, saveReservationAction, setDealStatusAction, setReservationStatusAction } from '@/actions/operations';

export function OperationsClient({ data }: { data: any }) {
  const [tab, setTab] = useState<'PUBLICATIONS'|'RESERVATIONS'|'DEALS'>('PUBLICATIONS');
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const [isPending, startTransition] = useTransition();

  function money(value: number | null, currency = 'ARS') {
    if (value == null) return '-';
    return `${currency} ${new Intl.NumberFormat('es-AR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)}`;
  }
  function run(task: () => Promise<any>) {
    setError(''); startTransition(async()=>{ try { await task(); window.location.reload(); } catch(err:any){ setError(err?.message||'No se pudo completar la operación.'); } });
  }

  function submitPublication(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>savePublicationAction({propertyId:String(f.get('propertyId')||''),channel:String(f.get('channel')||''),status:String(f.get('status')||'DRAFT') as any,url:String(f.get('url')||''),notes:String(f.get('notes')||'')}));}
  function submitReservation(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveReservationAction({propertyId:String(f.get('propertyId')||''),contactId:String(f.get('contactId')||''),leadId:String(f.get('leadId')||'')||null,agentId:String(f.get('agentId')||'')||null,amount:Number(f.get('amount')||0),currency:String(f.get('currency')||'ARS'),status:'PENDING',expiresAt:String(f.get('expiresAt')||'')||null,conditions:String(f.get('conditions')||''),commissionAmount:f.get('commissionAmount')?Number(f.get('commissionAmount')):null,notes:String(f.get('notes')||'')}));}
  function submitDeal(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveDealAction({propertyId:String(f.get('propertyId')||''),contactId:String(f.get('contactId')||'')||null,leadId:String(f.get('leadId')||'')||null,agentId:String(f.get('agentId')||'')||null,operation:String(f.get('operation')||'RENT') as any,status:'OPEN',amount:f.get('amount')?Number(f.get('amount')):null,currency:String(f.get('currency')||'ARS'),commissionAmount:f.get('commissionAmount')?Number(f.get('commissionAmount')):null,notes:String(f.get('notes')||'')}));}

  const activeReservations=data.reservations.filter((r:any)=>['PENDING','CONFIRMED'].includes(r.status)).length;
  const openDeals=data.deals.filter((d:any)=>['OPEN','NEGOTIATION'].includes(d.status)).length;
  const published=data.publications.filter((p:any)=>p.status==='PUBLISHED').length;

  return <div className="space-y-6">
    <div className="grid md:grid-cols-3 gap-4"><Metric icon={<RadioTower className="w-5 h-5"/>} label="Publicaciones activas" value={published}/><Metric icon={<BookOpenCheck className="w-5 h-5"/>} label="Reservas activas" value={activeReservations}/><Metric icon={<BadgeDollarSign className="w-5 h-5"/>} label="Operaciones abiertas" value={openDeals}/></div>
    <div className="flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><div className="flex bg-slate-100 rounded-lg p-1 overflow-x-auto"><Tab active={tab==='PUBLICATIONS'} onClick={()=>{setTab('PUBLICATIONS');setShowForm(false)}}>Publicaciones</Tab><Tab active={tab==='RESERVATIONS'} onClick={()=>{setTab('RESERVATIONS');setShowForm(false)}}>Reservas</Tab><Tab active={tab==='DEALS'} onClick={()=>{setTab('DEALS');setShowForm(false)}}>Operaciones</Tab></div><button onClick={()=>setShowForm(v=>!v)} className="action primary"><Plus className="w-4 h-4"/>Nuevo</button></div>
    {error&&<div className="p-3 bg-rose-50 border border-rose-100 rounded-lg text-sm text-rose-700">{error}</div>}

    {showForm&&tab==='PUBLICATIONS'&&<form onSubmit={submitPublication} className="card grid md:grid-cols-3 gap-3"><h2 className="md:col-span-3 font-bold">Nueva publicación</h2><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Field name="channel" label="Canal *" placeholder="Sitio propio, Zonaprop..."/><Select name="status" label="Estado" options={[['DRAFT','Borrador'],['PUBLISHED','Publicada'],['PAUSED','Pausada'],['ENDED','Finalizada']]}/><Field name="url" label="URL publicada" className="md:col-span-2"/><Field name="notes" label="Notas"/><div className="md:col-span-3 flex justify-end"><button disabled={isPending} className="submit">Guardar publicación</button></div></form>}
    {showForm&&tab==='RESERVATIONS'&&<form onSubmit={submitReservation} className="card grid md:grid-cols-4 gap-3"><h2 className="md:col-span-4 font-bold">Nueva reserva</h2><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Select name="contactId" label="Interesado *" options={data.contacts.map((c:any)=>[c.id,`${c.firstName} ${c.lastName}`])}/><Select name="leadId" label="Lead" options={[['','Sin lead'],...data.leads.map((l:any)=>[l.id,l.title])]}/><Select name="agentId" label="Agente" options={[['','Sin agente'],...data.users.map((u:any)=>[u.id,u.name])]}/><Field name="amount" label="Importe" type="number"/><Field name="currency" label="Moneda" defaultValue="ARS"/><Field name="expiresAt" label="Vence" type="datetime-local"/><Field name="commissionAmount" label="Comisión" type="number"/><Field name="conditions" label="Condiciones" className="md:col-span-2"/><Field name="notes" label="Notas" className="md:col-span-2"/><div className="md:col-span-4 flex justify-end"><button disabled={isPending} className="submit">Crear reserva</button></div></form>}
    {showForm&&tab==='DEALS'&&<form onSubmit={submitDeal} className="card grid md:grid-cols-4 gap-3"><h2 className="md:col-span-4 font-bold">Nueva operación</h2><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Select name="contactId" label="Contacto" options={[['','Sin contacto'],...data.contacts.map((c:any)=>[c.id,`${c.firstName} ${c.lastName}`])]}/><Select name="leadId" label="Lead" options={[['','Sin lead'],...data.leads.map((l:any)=>[l.id,l.title])]}/><Select name="agentId" label="Agente" options={[['','Sin agente'],...data.users.map((u:any)=>[u.id,u.name])]}/><Select name="operation" label="Operación" options={[['RENT','Alquiler'],['SALE','Venta'],['TEMPORARY_RENT','Temporal'],['MANAGEMENT','Administración']]}/><Field name="amount" label="Importe" type="number"/><Field name="currency" label="Moneda" defaultValue="ARS"/><Field name="commissionAmount" label="Comisión" type="number"/><Field name="notes" label="Notas" className="md:col-span-4"/><div className="md:col-span-4 flex justify-end"><button disabled={isPending} className="submit">Crear operación</button></div></form>}

    {tab==='PUBLICATIONS'&&<section className="card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b"><Th>Propiedad</Th><Th>Canal</Th><Th>Estado</Th><Th>Calidad</Th><Th>Métricas</Th><Th>URL</Th></tr></thead><tbody>{data.publications.map((p:any)=><tr key={p.id} className="border-b last:border-0"><Td><b>{p.property.code}</b><div className="text-xs text-slate-500">{p.property.address}</div></Td><Td>{p.channel}</Td><Td><Status value={p.status}/></Td><Td><span className="font-bold text-indigo-600">{p.completenessScore}%</span></Td><Td>{p.viewsCount} vistas · {p.inquiriesCount} consultas</Td><Td>{p.url?<a href={p.url} target="_blank" rel="noreferrer" className="text-indigo-600">Abrir</a>:'-'}</Td></tr>)}</tbody></table>{data.publications.length===0&&<Empty text="Todavía no hay publicaciones."/>}</div></section>}

    {tab==='RESERVATIONS'&&<div className="grid lg:grid-cols-2 gap-4">{data.reservations.map((r:any)=><article key={r.id} className="card"><div className="flex justify-between gap-3"><div><div className="flex gap-2 items-center"><h3 className="font-bold">{r.property.code}</h3><Status value={r.status}/></div><p className="text-xs text-slate-500 mt-1">{r.property.address}</p></div><p className="font-bold">{money(r.amount,r.currency)}</p></div><div className="mt-3 text-sm"><p>{r.contact.firstName} {r.contact.lastName}</p><p className="text-xs text-slate-500">{r.agent?.name||'Sin agente'}{r.expiresAt?` · vence ${new Date(r.expiresAt).toLocaleDateString('es-AR')}`:''}</p></div><div className="mt-4 flex flex-wrap gap-2">{r.status==='PENDING'&&<button onClick={()=>run(()=>setReservationStatusAction(r.id,'CONFIRMED'))} className="small">Confirmar</button>}{['PENDING','CONFIRMED'].includes(r.status)&&<button onClick={()=>run(()=>convertReservationToDealAction(r.id))} className="small primary">Convertir a operación <ArrowRight className="w-3 h-3"/></button>}{['PENDING','CONFIRMED'].includes(r.status)&&<button onClick={()=>run(()=>setReservationStatusAction(r.id,'CANCELED'))} className="small danger">Cancelar</button>}</div></article>)}{data.reservations.length===0&&<Empty text="Todavía no hay reservas."/>}</div>}

    {tab==='DEALS'&&<div className="grid lg:grid-cols-2 gap-4">{data.deals.map((d:any)=><article key={d.id} className="card"><div className="flex justify-between gap-3"><div><div className="flex gap-2 items-center"><h3 className="font-bold">{d.property.code} · {d.operation}</h3><Status value={d.status}/></div><p className="text-xs text-slate-500 mt-1">{d.property.address}</p></div><p className="font-bold">{money(d.amount,d.currency)}</p></div><p className="text-sm mt-3">{d.contact?`${d.contact.firstName} ${d.contact.lastName}`:'Sin contacto'} · {d.agent?.name||'Sin agente'}</p>{d.propertyLease&&<p className="text-xs text-emerald-600 mt-2 font-semibold"><CheckCircle2 className="inline w-3.5 h-3.5 mr-1"/>Contrato vinculado</p>}<div className="mt-4 flex flex-wrap gap-2">{d.status==='OPEN'&&<button onClick={()=>run(()=>setDealStatusAction(d.id,'NEGOTIATION'))} className="small">Negociación</button>}{['OPEN','NEGOTIATION'].includes(d.status)&&<button onClick={()=>run(()=>setDealStatusAction(d.id,'WON'))} className="small primary">Cerrar ganada</button>}{['OPEN','NEGOTIATION'].includes(d.status)&&<button onClick={()=>run(()=>setDealStatusAction(d.id,'LOST'))} className="small danger">Perdida</button>}</div></article>)}{data.deals.length===0&&<Empty text="Todavía no hay operaciones."/>}</div>}
    <style jsx>{`.card{background:white;border:1px solid #e2e8f0;border-radius:.75rem;padding:1.25rem}.action{display:inline-flex;align-items:center;gap:.4rem;padding:.55rem .85rem;border:1px solid #e2e8f0;border-radius:.5rem;font-size:.8rem;font-weight:600}.primary,.submit{background:#4f46e5;color:white;border-color:#4f46e5}.submit{padding:.55rem 1rem;border-radius:.5rem;font-size:.8rem;font-weight:600}.small{display:inline-flex;align-items:center;gap:.3rem;padding:.4rem .65rem;border:1px solid #e2e8f0;border-radius:.45rem;font-size:.72rem;font-weight:600}.danger{color:#e11d48;border-color:#fecdd3}`}</style>
  </div>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="bg-white border border-slate-200 rounded-xl p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center">{icon}</div><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`px-4 py-2 rounded-md text-xs font-bold whitespace-nowrap ${active?'bg-white shadow-xs text-slate-900':'text-slate-500'}`}>{children}</button>}
function Field({name,label,type='text',placeholder,defaultValue,className=''}:{name:string;label:string;type?:string;placeholder?:string;defaultValue?:string;className?:string}){return <label className={className}><span className="block text-xs font-semibold text-slate-700 mb-1">{label}</span><input name={name} type={type} placeholder={placeholder} defaultValue={defaultValue} className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"/></label>}
function Select({name,label,options}:{name:string;label:string;options:any[]}){return <label><span className="block text-xs font-semibold text-slate-700 mb-1">{label}</span><select name={name} className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm bg-white">{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function Status({value}:{value:string}){return <span className="px-2 py-0.5 bg-slate-100 rounded-full text-[10px] font-bold text-slate-600">{value}</span>}
function Th({children}:{children:React.ReactNode}){return <th className="py-3 pr-4 font-semibold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="py-3 pr-4 align-top">{children}</td>}
function Empty({text}:{text:string}){return <div className="py-12 text-center text-sm text-slate-400">{text}</div>}
