'use client';

import { useState,useTransition } from 'react';
import { CopyPlus, FileSignature, Workflow } from 'lucide-react';
import { createDocumentVersionAction,requestDocumentSignatureAction,setDocumentWorkflowStatusAction } from '@/actions/document-workflow';

const STATUSES=['DRAFT','GENERATED','SENT','VIEWED','SIGNED','ARCHIVED'] as const;
const LABELS:Record<string,string>={DRAFT:'Borrador',GENERATED:'Generado',SENT:'Enviado',VIEWED:'Visto',SIGNED:'Firmado',ARCHIVED:'Archivado'};
export function DocumentWorkflowPanel({documents}:{documents:any[]}){
 const[error,setError]=useState(''),[pending,startTransition]=useTransition();
 const run=(fn:()=>Promise<any>)=>startTransition(async()=>{try{setError('');await fn();location.reload()}catch(e:any){setError(e?.message||'No se pudo actualizar el documento.')}});
 return <section className="section-card mb-6"><div className="section-card__header"><div><div className="flex items-center gap-2"><Workflow className="w-5 h-5 text-indigo-600"/><h2 className="section-card__title">Workflow documental</h2></div><p className="section-card__subtitle">Versiones, trazabilidad y estado de firma.</p></div></div><div className="section-card__body">{error&&<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="table-shell"><table className="data-table"><thead><tr><th>Documento</th><th>Vínculo</th><th>Versión</th><th>Estado</th><th>Firma</th><th>Acciones</th></tr></thead><tbody>{documents.length?documents.map((d:any)=><tr key={d.id}><td><a href={d.fileUrl} target="_blank" rel="noreferrer" className="font-semibold text-indigo-600">{d.fileName}</a><div className="text-[10px] text-slate-400">{d.category} · {new Date(d.uploadedAt).toLocaleDateString('es-AR')}</div></td><td>{d.propertyCode?`${d.propertyCode} · ${d.propertyAddress}`:(d.renterName||'—')}</td><td>v{d.version}</td><td><select value={d.workflowStatus} disabled={pending} onChange={e=>run(()=>setDocumentWorkflowStatusAction(d.id,e.target.value as any))} className="form-input py-1 text-xs">{STATUSES.map(s=><option key={s} value={s}>{LABELS[s]}</option>)}</select></td><td>{d.signatureExternalId?<div><span className="status-pill status-pill--info">{d.signatureProvider||'Firma'}</span><div className="text-[10px] text-slate-400 mt-1 font-mono">{d.signatureExternalId}</div></div>:'—'}</td><td><div className="flex gap-1"><button title="Nueva versión" onClick={()=>run(()=>createDocumentVersionAction(d.id))} className="icon-action"><CopyPlus className="w-4 h-4"/></button><button title="Enviar a firma" onClick={()=>run(()=>requestDocumentSignatureAction(d.id))} className="icon-action"><FileSignature className="w-4 h-4"/></button></div></td></tr>):<tr><td colSpan={6} className="text-center text-slate-400 py-8">Todavía no hay documentos.</td></tr>}</tbody></table></div></div></section>
}
