import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft,Building2,CalendarDays,FileText,Handshake,MessageSquare,UserRound } from 'lucide-react';
import { getOperation360Action } from '@/actions/operation-360';
import { DataTable,DetailGrid,EntityHero,MetricCard,SectionCard,StatusPill,Timeline } from '@/components/entity-360/entity-360-ui';

export const dynamic='force-dynamic';
const money=(v:any,c='ARS')=>v==null?'—':new Intl.NumberFormat('es-AR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v));
const date=(v:any)=>v?new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date(v)):'—';
const name=(p:any)=>p?(p.companyName||`${p.firstName||''} ${p.lastName||''}`.trim()||'—'):'—';
function tone(s?:string):'neutral'|'success'|'warning'|'danger'|'info'{if(!s)return'neutral';if(['WON','CURRENT','CONFIRMED','CONVERTED','PUBLISHED'].includes(s))return'success';if(['LOST','CANCELED','EXPIRED','ENDED'].includes(s))return'danger';if(['OPEN','NEGOTIATION','PENDING','RESERVED'].includes(s))return'warning';return'info'}

export default async function Operation360Page({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const data:any=await getOperation360Action(id);if(!data)notFound();const d=data.deal;const leaseDebt=d.propertyLease?.debts?.reduce((s:number,x:any)=>s+Math.max(0,Number(x.amount)-Number(x.paidAmount)),0)||0;
 return <div className="app-page"><div className="page-container space-y-6">
  <Link href="/operaciones" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="w-4 h-4"/> Operaciones</Link>
  <EntityHero eyebrow="Operación 360" title={`${d.operation} · ${d.property.code} · ${d.property.address}`} subtitle={`${name(d.contact)} · ${d.agent?.name||'Sin agente'}`} badges={[{label:d.status,tone:tone(d.status)},{label:d.operation,tone:'info'}]} actions={<><Link href={`/propiedades/${d.propertyId}`} className="btn-primary"><Building2 className="w-4 h-4"/> Propiedad 360</Link>{d.propertyLease&&<Link href={`/contratos/${d.propertyLease.id}`} className="btn-secondary"><FileText className="w-4 h-4"/> Contrato 360</Link>}</>} media={<div className="entity-hero__placeholder"><Handshake className="w-12 h-12"/><span>Operación</span></div>}/>
  <div className="grid grid-cols-2 xl:grid-cols-5 gap-3"><MetricCard label="Importe" value={money(d.amount,d.currency)} detail={d.currency}/><MetricCard label="Comisión" value={money(d.commissionAmount,d.currency)} detail={d.commissionPercent?`${Number(d.commissionPercent).toFixed(2)}%`:'Configuración manual'}/><MetricCard label="Contacto" value={name(d.contact)} detail={d.contact?.documentNumber||d.contact?.cuit||'Sin documento'} icon={<UserRound className="w-5 h-5"/>}/><MetricCard label="Reserva" value={d.reservation?d.reservation.status:'Sin reserva'} detail={d.reservation?money(d.reservation.amount,d.reservation.currency):'—'}/><MetricCard label="Saldo contrato" value={money(leaseDebt)} detail={d.propertyLease?d.propertyLease.status:'Sin contrato'}/></div>
  <div className="grid xl:grid-cols-3 gap-5"><SectionCard title="Negocio" subtitle="Condiciones de cierre"><DetailGrid items={[{label:'Estado',value:d.status},{label:'Operación',value:d.operation},{label:'Importe',value:money(d.amount,d.currency)},{label:'Comisión',value:money(d.commissionAmount,d.currency)},{label:'Cierre',value:date(d.closedAt)},{label:'Creación',value:date(d.createdAt)},{label:'Condiciones',value:d.terms||'—'},{label:'Notas',value:d.notes||'—'}]}/></SectionCard><SectionCard title="Interesado" subtitle="Contacto y origen"><Link href={`/contactos/${d.contactId}`} className="font-bold text-indigo-600">{name(d.contact)}</Link><DetailGrid items={[{label:'Documento',value:d.contact?.documentNumber||d.contact?.cuit||'—'},{label:'Email',value:d.contact?.email||'—'},{label:'Teléfono',value:d.contact?.phone||'—'},{label:'Lead',value:d.lead?.title||'—'},{label:'Agente',value:d.agent?.name||'—'}]}/></SectionCard><SectionCard title="Propietarios" subtitle="Titularidad de la propiedad"><div className="space-y-2">{d.property.owners.map((o:any)=><Link key={o.id} href={`/contactos/${o.contactId}`} className="flex justify-between rounded-xl border p-3"><span className="text-sm font-semibold">{name(o.contact)}</span><span className="font-mono text-xs">{Number(o.ownershipPercentage).toFixed(2)}%</span></Link>)}</div></SectionCard></div>
  {d.lead&&<SectionCard title="Historial comercial" subtitle="Interacciones y propiedades evaluadas"><div className="grid xl:grid-cols-2 gap-5"><DataTable headers={['Fecha','Tipo','Detalle']} rows={d.lead.interactions.map((i:any)=>[date(i.occurredAt),i.type,i.summary||i.notes||'—'])}/><DataTable headers={['Propiedad','Score','Estado']} rows={d.lead.propertyInterests.map((i:any)=>[<Link key="p" href={`/propiedades/${i.property.id}`} className="font-semibold text-indigo-600">{i.property.code} · {i.property.address}</Link>,i.score,<StatusPill key="s" tone={tone(i.status)}>{i.status}</StatusPill>])}/></div></SectionCard>}
  <SectionCard title="Publicación y documentos" subtitle="Contexto comercial del activo"><div className="grid xl:grid-cols-2 gap-5"><DataTable headers={['Canal','URL','Estado']} rows={d.property.publications.map((p:any)=>[p.channel,p.url?<a key="u" href={p.url} target="_blank" rel="noreferrer" className="text-indigo-600">Abrir</a>:'—',<StatusPill key="s" tone={tone(p.status)}>{p.status}</StatusPill>])}/><DataTable headers={['Documento','Categoría','Fecha']} rows={d.documents.map((doc:any)=>[<a key="d" href={doc.fileUrl} target="_blank" rel="noreferrer" className="font-semibold text-indigo-600">{doc.fileName}</a>,doc.category,date(doc.uploadedAt)])}/></div></SectionCard>
  <SectionCard title="Comunicaciones" subtitle="Conversaciones vinculadas a la operación"><DataTable headers={['Asunto','Mensajes','Última actividad','Estado']} rows={data.communications.map((t:any)=>[t.subject,Number(t.messageCount||0),date(t.lastMessageAt||t.updatedAt),<StatusPill key="s" tone={tone(t.status)}>{t.status}</StatusPill>])}/></SectionCard>
  <SectionCard title="Actividad 360" subtitle="Timeline comercial y operativo"><Timeline items={data.activity.map((e:any)=>({id:e.id,title:e.title,detail:e.description,date:e.createdAt,actor:e.actorName}))}/></SectionCard>
 </div></div>
}
