'use client';

import { useState, useTransition } from 'react';
import { CircleDollarSign, Plus, ReceiptText, Repeat2, WalletCards } from 'lucide-react';
import { createOwnerSettlementAction, generateRecurringChargesAction, savePropertyExpenseAction, saveRecurringChargeAction, setOwnerSettlementStatusAction, setPropertyExpenseStatusAction } from '@/actions/property-management';

export function PropertyManagementClient({ data }: { data: any }) {
  const [tab, setTab] = useState<'EXPENSES'|'RECURRING'|'SETTLEMENTS'>('EXPENSES');
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [isPending, startTransition] = useTransition();

  const run = (task: () => Promise<any>, reload = true) => {
    setError(''); setMessage('');
    startTransition(async()=>{ try { const result=await task(); if(reload) window.location.reload(); else setMessage(`Generación completada: ${result.created} cargos.`); } catch(err:any){ setError(err?.message||'No se pudo completar la operación.'); } });
  };
  const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(v||0);

  function submitExpense(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>savePropertyExpenseAction({propertyId:String(f.get('propertyId')||''),providerContactId:String(f.get('providerContactId')||'')||null,ownerContactId:String(f.get('ownerContactId')||'')||null,category:String(f.get('category')||''),description:String(f.get('description')||''),amount:Number(f.get('amount')||0),dueDate:String(f.get('dueDate')||'')||null,status:'PENDING',chargeToRenter:f.get('chargeToRenter')==='on',chargeToOwner:f.get('chargeToOwner')==='on',documentUrl:String(f.get('documentUrl')||''),notes:String(f.get('notes')||'')}));}
  function submitRecurring(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveRecurringChargeAction({propertyLeaseId:String(f.get('propertyLeaseId')||''),type:String(f.get('type')||'EXPENSAS') as any,description:String(f.get('description')||''),amount:f.get('amount')?Number(f.get('amount')):null,percentage:f.get('percentage')?Number(f.get('percentage')):null,frequencyMonths:Number(f.get('frequencyMonths')||1),dueDay:Number(f.get('dueDay')||10),startsAt:String(f.get('startsAt')||''),endsAt:String(f.get('endsAt')||'')||null,active:true}));}
  function submitSettlement(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createOwnerSettlementAction({ownerContactId:String(f.get('ownerContactId')||''),periodStart:String(f.get('periodStart')||''),periodEnd:String(f.get('periodEnd')||''),taxPercent:f.get('taxPercent')?Number(f.get('taxPercent')):0,notes:String(f.get('notes')||'')}));}
  function generate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>generateRecurringChargesAction(String(f.get('period')||'')),false);}

  const pendingExpenses=data.expenses.filter((e:any)=>e.status==='PENDING').reduce((s:number,e:any)=>s+e.amount,0);
  const readySettlements=data.settlements.filter((s:any)=>s.status==='READY').reduce((sum:number,s:any)=>sum+s.netAmount,0);
  const activeRules=data.recurringCharges.filter((r:any)=>r.active).length;

  return <div className="space-y-6">
    <div className="grid md:grid-cols-3 gap-4"><Metric icon={<ReceiptText className="w-5 h-5"/>} label="Gastos pendientes" value={money(pendingExpenses)}/><Metric icon={<Repeat2 className="w-5 h-5"/>} label="Cargos recurrentes activos" value={String(activeRules)}/><Metric icon={<WalletCards className="w-5 h-5"/>} label="A liquidar" value={money(readySettlements)}/></div>
    <div className="flex flex-col md:flex-row gap-3 justify-between"><div className="flex bg-slate-100 rounded-lg p-1 overflow-x-auto"><Tab active={tab==='EXPENSES'} onClick={()=>{setTab('EXPENSES');setShowForm(false)}}>Gastos</Tab><Tab active={tab==='RECURRING'} onClick={()=>{setTab('RECURRING');setShowForm(false)}}>Cargos recurrentes</Tab><Tab active={tab==='SETTLEMENTS'} onClick={()=>{setTab('SETTLEMENTS');setShowForm(false)}}>Liquidaciones</Tab></div><button onClick={()=>setShowForm(v=>!v)} className="action primary"><Plus className="w-4 h-4"/>Nuevo</button></div>
    {error&&<div className="p-3 bg-rose-50 border border-rose-100 rounded-lg text-sm text-rose-700">{error}</div>}{message&&<div className="p-3 bg-emerald-50 border border-emerald-100 rounded-lg text-sm text-emerald-700">{message}</div>}

    {showForm&&tab==='EXPENSES'&&<form onSubmit={submitExpense} className="card grid md:grid-cols-4 gap-3"><h2 className="md:col-span-4 font-bold">Nuevo gasto</h2><Select name="propertyId" label="Propiedad *" options={data.properties.map((p:any)=>[p.id,`${p.code} · ${p.address}`])}/><Select name="providerContactId" label="Proveedor" options={[['','Sin proveedor'],...data.providers.map((p:any)=>[p.id,p.companyName||`${p.firstName} ${p.lastName}`])]}/><Select name="ownerContactId" label="Propietario" options={[['','Distribución general'],...data.owners.map((o:any)=>[o.id,`${o.firstName} ${o.lastName}`])]}/><Field name="category" label="Categoría *" placeholder="Impuesto, reparación..."/><Field name="description" label="Descripción *" className="md:col-span-2"/><Field name="amount" label="Importe *" type="number"/><Field name="dueDate" label="Vencimiento" type="date"/><Field name="documentUrl" label="Comprobante URL" className="md:col-span-2"/><Field name="notes" label="Notas"/><div className="flex items-end gap-4 pb-2"><Check name="chargeToOwner" label="A cargo propietario" defaultChecked/><Check name="chargeToRenter" label="Repercutir inquilino"/></div><div className="md:col-span-4 flex justify-end"><button className="submit" disabled={isPending}>Guardar gasto</button></div></form>}

    {showForm&&tab==='RECURRING'&&<form onSubmit={submitRecurring} className="card grid md:grid-cols-4 gap-3"><h2 className="md:col-span-4 font-bold">Nuevo cargo recurrente</h2><Select name="propertyLeaseId" label="Contrato *" options={data.leases.map((l:any)=>[l.id,`${l.property.code} · ${l.renter.firstName} ${l.renter.lastName}`])}/><Select name="type" label="Tipo" options={[['EXPENSAS','Expensas'],['LUZ','Luz'],['GAS','Gas'],['AGUA','Agua'],['SEGURO','Seguro'],['IMPUESTO','Impuesto'],['PENALIDAD','Penalidad'],['OTROS','Otros']]}/><Field name="description" label="Descripción *"/><Field name="amount" label="Importe fijo" type="number"/><Field name="percentage" label="% sobre alquiler" type="number"/><Field name="frequencyMonths" label="Cada N meses" type="number" defaultValue="1"/><Field name="dueDay" label="Día vencimiento" type="number" defaultValue="10"/><Field name="startsAt" label="Desde *" type="date"/><Field name="endsAt" label="Hasta" type="date"/><div className="md:col-span-4 flex justify-end"><button className="submit" disabled={isPending}>Guardar regla</button></div></form>}

    {showForm&&tab==='SETTLEMENTS'&&<form onSubmit={submitSettlement} className="card grid md:grid-cols-4 gap-3"><h2 className="md:col-span-4 font-bold">Generar liquidación</h2><Select name="ownerContactId" label="Propietario *" options={data.owners.map((o:any)=>[o.id,`${o.firstName} ${o.lastName}`])}/><Field name="periodStart" label="Desde *" type="date"/><Field name="periodEnd" label="Hasta *" type="date"/><Field name="taxPercent" label="Retenciones %" type="number" defaultValue="0"/><Field name="notes" label="Notas" className="md:col-span-4"/><div className="md:col-span-4 flex justify-end"><button className="submit" disabled={isPending}>Calcular y generar</button></div></form>}

    {tab==='EXPENSES'&&<section className="card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b"><Th>Propiedad</Th><Th>Concepto</Th><Th>Proveedor</Th><Th>Importe</Th><Th>Estado</Th><Th>Acción</Th></tr></thead><tbody>{data.expenses.map((e:any)=><tr key={e.id} className="border-b last:border-0"><Td><b>{e.property.code}</b><div className="text-xs text-slate-500">{e.property.address}</div></Td><Td>{e.category}<div className="text-xs text-slate-500">{e.description}</div></Td><Td>{e.provider?(e.provider.companyName||`${e.provider.firstName} ${e.provider.lastName}`):'-'}</Td><Td>{money(e.amount)}</Td><Td><Status value={e.status}/></Td><Td>{e.status==='PENDING'&&<button onClick={()=>run(()=>setPropertyExpenseStatusAction(e.id,'PAID'))} className="small">Marcar pagado</button>}</Td></tr>)}</tbody></table>{data.expenses.length===0&&<Empty text="No hay gastos registrados."/>}</div></section>}

    {tab==='RECURRING'&&<div className="space-y-4"><form onSubmit={generate} className="card flex flex-col md:flex-row md:items-end gap-3"><Field name="period" label="Generar cargos del período" type="month" defaultValue={new Date().toISOString().slice(0,7)}/><button disabled={isPending} className="submit">Generar deudas</button></form><section className="card"><div className="space-y-2">{data.recurringCharges.map((r:any)=><div key={r.id} className="p-3 border rounded-lg flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="text-sm font-semibold">{r.description}</p><p className="text-xs text-slate-500">{r.lease.property.code} · {r.lease.renter.firstName} {r.lease.renter.lastName} · cada {r.frequencyMonths} mes/es</p></div><div className="text-right"><p className="font-bold text-sm">{r.amount!=null?money(r.amount):`${r.percentage}% alquiler`}</p><Status value={r.active?'ACTIVO':'INACTIVO'}/></div></div>)}{data.recurringCharges.length===0&&<Empty text="No hay cargos recurrentes."/>}</div></section></div>}

    {tab==='SETTLEMENTS'&&<div className="space-y-4">{data.settlements.map((s:any)=><article key={s.id} className="card"><div className="flex flex-col md:flex-row md:items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-bold">{s.owner.firstName} {s.owner.lastName}</h3><Status value={s.status}/></div><p className="text-xs text-slate-500 mt-1">{new Date(s.periodStart).toLocaleDateString('es-AR')} — {new Date(s.periodEnd).toLocaleDateString('es-AR')}</p></div><div className="text-right"><p className="text-xs text-slate-500">Neto propietario</p><p className="text-xl font-bold text-indigo-600">{money(s.netAmount)}</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Mini label="Cobrado" value={money(s.grossCollected)}/><Mini label="Gastos" value={money(s.expensesTotal)}/><Mini label="Comisión" value={money(s.commissionTotal)}/><Mini label="Retenciones" value={money(s.taxesTotal)}/></div><details className="mt-4"><summary className="text-xs font-semibold text-slate-600 cursor-pointer">Ver detalle ({s.lines.length})</summary><div className="mt-2 divide-y border rounded-lg">{s.lines.map((l:any)=><div key={l.id} className="p-2 flex justify-between text-xs"><span>{l.property?.code?`${l.property.code} · `:''}{l.description}</span><span className={l.amount<0?'text-rose-600':'text-emerald-600'}>{money(l.amount)}</span></div>)}</div></details>{s.status==='READY'&&<div className="mt-4 flex justify-end"><button onClick={()=>run(()=>setOwnerSettlementStatusAction(s.id,'PAID'))} className="small primary"><CircleDollarSign className="w-3.5 h-3.5"/>Marcar liquidada</button></div>}</article>)}{data.settlements.length===0&&<Empty text="Todavía no hay liquidaciones."/>}</div>}
    <style jsx>{`.card{background:white;border:1px solid #e2e8f0;border-radius:.75rem;padding:1.25rem}.action{display:inline-flex;align-items:center;gap:.4rem;padding:.55rem .85rem;border:1px solid #e2e8f0;border-radius:.5rem;font-size:.8rem;font-weight:600}.primary,.submit{background:#4f46e5;color:white;border-color:#4f46e5}.submit{padding:.55rem 1rem;border-radius:.5rem;font-size:.8rem;font-weight:600}.small{display:inline-flex;align-items:center;gap:.3rem;padding:.4rem .65rem;border:1px solid #e2e8f0;border-radius:.45rem;font-size:.72rem;font-weight:600}`}</style>
  </div>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="bg-white border border-slate-200 rounded-xl p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center">{icon}</div><div><p className="text-xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`px-4 py-2 rounded-md text-xs font-bold whitespace-nowrap ${active?'bg-white shadow-xs text-slate-900':'text-slate-500'}`}>{children}</button>}
function Field({name,label,type='text',placeholder,defaultValue,className=''}:{name:string;label:string;type?:string;placeholder?:string;defaultValue?:string;className?:string}){return <label className={className}><span className="block text-xs font-semibold text-slate-700 mb-1">{label}</span><input name={name} type={type} placeholder={placeholder} defaultValue={defaultValue} className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"/></label>}
function Select({name,label,options}:{name:string;label:string;options:any[]}){return <label><span className="block text-xs font-semibold text-slate-700 mb-1">{label}</span><select name={name} className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm bg-white">{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function Check({name,label,defaultChecked}:{name:string;label:string;defaultChecked?:boolean}){return <label className="flex items-center gap-2 text-xs text-slate-600"><input name={name} type="checkbox" defaultChecked={defaultChecked}/>{label}</label>}
function Status({value}:{value:string}){return <span className="px-2 py-0.5 bg-slate-100 rounded-full text-[10px] font-bold text-slate-600">{value}</span>}
function Th({children}:{children:React.ReactNode}){return <th className="py-3 pr-4 font-semibold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="py-3 pr-4 align-top">{children}</td>}
function Empty({text}:{text:string}){return <div className="py-12 text-center text-sm text-slate-400">{text}</div>}
function Mini({label,value}:{label:string;value:string}){return <div className="bg-slate-50 rounded-lg p-3"><p className="text-[10px] uppercase font-bold text-slate-400">{label}</p><p className="font-semibold text-sm mt-1">{value}</p></div>}
