-- Phase 2: CRM inmobiliario, matching, agenda, publicaciones, reservas,
-- operaciones, administración de gastos y liquidaciones a propietarios.
-- Migration is additive and preserves all Phase 1 / legacy data.

ALTER TABLE `PropertyLease`
  MODIFY `status` ENUM('DRAFT','CURRENT','EXPIRING','RENEWED','TERMINATED','CANCELED') NOT NULL DEFAULT 'CURRENT',
  ADD COLUMN `guarantorContactId` VARCHAR(191) NULL,
  ADD COLUMN `extensionUntil` DATE NULL,
  ADD COLUMN `adjustmentMethod` VARCHAR(40) NOT NULL DEFAULT 'FIXED_PERCENT',
  ADD COLUMN `adjustmentIndex` VARCHAR(40) NULL,
  ADD COLUMN `nextAdjustmentDate` DATE NULL,
  ADD COLUMN `guaranteeType` VARCHAR(80) NULL,
  ADD COLUMN `guaranteeDetails` TEXT NULL,
  ADD COLUMN `renewalReference` VARCHAR(120) NULL,
  ADD COLUMN `entryChecklist` JSON NULL,
  ADD COLUMN `exitChecklist` JSON NULL,
  ADD COLUMN `inventoryNotes` TEXT NULL;

ALTER TABLE `GarageLease`
  MODIFY `status` ENUM('DRAFT','CURRENT','EXPIRING','RENEWED','TERMINATED','CANCELED') NOT NULL DEFAULT 'CURRENT';

ALTER TABLE `Debt`
  MODIFY `type` ENUM('ALQUILER','EXPENSAS','DEPOSITO','LUZ','GAS','AGUA','SEGURO','IMPUESTO','PENALIDAD','INTERES','NOTA_DEBITO','NOTA_CREDITO','OTROS') NOT NULL DEFAULT 'ALQUILER';

CREATE INDEX `PropertyLease_tenantId_nextAdjustmentDate_idx` ON `PropertyLease`(`tenantId`,`nextAdjustmentDate`);
CREATE INDEX `PropertyLease_guarantorContactId_idx` ON `PropertyLease`(`guarantorContactId`);
ALTER TABLE `PropertyLease`
  ADD CONSTRAINT `PropertyLease_guarantorContactId_fkey` FOREIGN KEY (`guarantorContactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE `Lead` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `contactId` VARCHAR(191) NOT NULL,
  `agentId` VARCHAR(191) NULL,
  `title` VARCHAR(180) NOT NULL,
  `source` VARCHAR(100) NULL,
  `channel` VARCHAR(60) NULL,
  `priority` ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
  `score` INTEGER NULL,
  `status` ENUM('NEW','CONTACTED','QUALIFIED','PROPERTIES_SENT','VISIT_SCHEDULED','VISITED','NEGOTIATION','RESERVATION','WON','LOST') NOT NULL DEFAULT 'NEW',
  `notes` TEXT NULL,
  `nextStep` VARCHAR(255) NULL,
  `nextActionAt` DATETIME(3) NULL,
  `firstResponseAt` DATETIME(3) NULL,
  `lastInteractionAt` DATETIME(3) NULL,
  `closedAt` DATETIME(3) NULL,
  `lostReason` VARCHAR(255) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Lead_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `Lead_tenantId_agentId_status_idx` (`tenantId`,`agentId`,`status`),
  INDEX `Lead_tenantId_nextActionAt_idx` (`tenantId`,`nextActionAt`),
  INDEX `Lead_contactId_idx` (`contactId`),
  CONSTRAINT `Lead_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Lead_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Lead_agentId_fkey` FOREIGN KEY (`agentId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LeadInteraction` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NULL,
  `type` ENUM('CALL','WHATSAPP','EMAIL','MEETING','NOTE','OTHER') NOT NULL DEFAULT 'NOTE',
  `summary` TEXT NOT NULL,
  `nextStep` VARCHAR(255) NULL,
  `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `LeadInteraction_tenantId_occurredAt_idx` (`tenantId`,`occurredAt`),
  INDEX `LeadInteraction_leadId_occurredAt_idx` (`leadId`,`occurredAt`),
  CONSTRAINT `LeadInteraction_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LeadInteraction_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LeadInteraction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Demand` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NULL,
  `contactId` VARCHAR(191) NOT NULL,
  `operation` ENUM('RENT','SALE','TEMPORARY_RENT','MANAGEMENT') NOT NULL,
  `propertyType` ENUM('DEPARTAMENTO','CASA','LOCAL','TERRENO','OFICINA','COCHERA','OTRO') NULL,
  `zones` JSON NULL,
  `budgetMin` DECIMAL(14,2) NULL,
  `budgetMax` DECIMAL(14,2) NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'ARS',
  `roomsMin` INTEGER NULL,
  `bedroomsMin` INTEGER NULL,
  `sqmMin` DECIMAL(10,2) NULL,
  `amenities` JSON NULL,
  `excludedConditions` TEXT NULL,
  `status` ENUM('ACTIVE','PAUSED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Demand_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `Demand_tenantId_operation_propertyType_idx` (`tenantId`,`operation`,`propertyType`),
  INDEX `Demand_contactId_idx` (`contactId`),
  INDEX `Demand_leadId_idx` (`leadId`),
  CONSTRAINT `Demand_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Demand_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Demand_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LeadPropertyInterest` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NOT NULL,
  `score` INTEGER NOT NULL DEFAULT 0,
  `matchReasons` JSON NULL,
  `status` ENUM('MATCHED','SENT','FAVORITE','REJECTED') NOT NULL DEFAULT 'MATCHED',
  `sentAt` DATETIME(3) NULL,
  `respondedAt` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `LeadPropertyInterest_leadId_propertyId_key` (`leadId`,`propertyId`),
  INDEX `LeadPropertyInterest_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `LeadPropertyInterest_propertyId_idx` (`propertyId`),
  CONSTRAINT `LeadPropertyInterest_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LeadPropertyInterest_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LeadPropertyInterest_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Task` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NULL,
  `contactId` VARCHAR(191) NULL,
  `propertyId` VARCHAR(191) NULL,
  `assignedUserId` VARCHAR(191) NULL,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `dueAt` DATETIME(3) NULL,
  `status` ENUM('OPEN','IN_PROGRESS','DONE','CANCELED') NOT NULL DEFAULT 'OPEN',
  `priority` ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
  `recurrenceRule` VARCHAR(255) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Task_tenantId_status_dueAt_idx` (`tenantId`,`status`,`dueAt`),
  INDEX `Task_assignedUserId_status_idx` (`assignedUserId`,`status`),
  INDEX `Task_leadId_idx` (`leadId`),
  CONSTRAINT `Task_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Task_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Task_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Task_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Task_assignedUserId_fkey` FOREIGN KEY (`assignedUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CalendarEvent` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NULL,
  `contactId` VARCHAR(191) NULL,
  `propertyId` VARCHAR(191) NULL,
  `agentId` VARCHAR(191) NULL,
  `type` ENUM('VISIT','MEETING','CALL','OTHER') NOT NULL DEFAULT 'VISIT',
  `status` ENUM('SCHEDULED','COMPLETED','CANCELED','NO_SHOW') NOT NULL DEFAULT 'SCHEDULED',
  `title` VARCHAR(180) NOT NULL,
  `startsAt` DATETIME(3) NOT NULL,
  `endsAt` DATETIME(3) NULL,
  `location` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CalendarEvent_tenantId_startsAt_idx` (`tenantId`,`startsAt`),
  INDEX `CalendarEvent_tenantId_status_startsAt_idx` (`tenantId`,`status`,`startsAt`),
  INDEX `CalendarEvent_agentId_startsAt_idx` (`agentId`,`startsAt`),
  CONSTRAINT `CalendarEvent_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CalendarEvent_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `CalendarEvent_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `CalendarEvent_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `CalendarEvent_agentId_fkey` FOREIGN KEY (`agentId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Publication` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NOT NULL,
  `channel` VARCHAR(80) NOT NULL,
  `status` ENUM('DRAFT','PUBLISHED','PAUSED','ENDED') NOT NULL DEFAULT 'DRAFT',
  `url` VARCHAR(500) NULL,
  `completenessScore` INTEGER NOT NULL DEFAULT 0,
  `viewsCount` INTEGER NOT NULL DEFAULT 0,
  `inquiriesCount` INTEGER NOT NULL DEFAULT 0,
  `publishedAt` DATETIME(3) NULL,
  `unpublishedAt` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Publication_tenantId_propertyId_channel_key` (`tenantId`,`propertyId`,`channel`),
  INDEX `Publication_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `Publication_propertyId_idx` (`propertyId`),
  CONSTRAINT `Publication_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Publication_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Reservation` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NOT NULL,
  `contactId` VARCHAR(191) NOT NULL,
  `leadId` VARCHAR(191) NULL,
  `agentId` VARCHAR(191) NULL,
  `amount` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'ARS',
  `status` ENUM('PENDING','CONFIRMED','EXPIRED','CANCELED','CONVERTED') NOT NULL DEFAULT 'PENDING',
  `expiresAt` DATETIME(3) NULL,
  `conditions` TEXT NULL,
  `commissionAmount` DECIMAL(14,2) NULL,
  `notes` TEXT NULL,
  `convertedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Reservation_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `Reservation_tenantId_expiresAt_idx` (`tenantId`,`expiresAt`),
  INDEX `Reservation_propertyId_idx` (`propertyId`),
  CONSTRAINT `Reservation_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Reservation_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Reservation_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Reservation_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Reservation_agentId_fkey` FOREIGN KEY (`agentId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Deal` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NOT NULL,
  `contactId` VARCHAR(191) NULL,
  `leadId` VARCHAR(191) NULL,
  `reservationId` VARCHAR(191) NULL,
  `agentId` VARCHAR(191) NULL,
  `propertyLeaseId` VARCHAR(191) NULL,
  `operation` ENUM('RENT','SALE','TEMPORARY_RENT','MANAGEMENT') NOT NULL,
  `status` ENUM('OPEN','NEGOTIATION','WON','LOST','CANCELED') NOT NULL DEFAULT 'OPEN',
  `amount` DECIMAL(14,2) NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'ARS',
  `commissionAmount` DECIMAL(14,2) NULL,
  `closedAt` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Deal_reservationId_key` (`reservationId`),
  UNIQUE INDEX `Deal_propertyLeaseId_key` (`propertyLeaseId`),
  INDEX `Deal_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `Deal_tenantId_operation_idx` (`tenantId`,`operation`),
  INDEX `Deal_propertyId_idx` (`propertyId`),
  CONSTRAINT `Deal_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Deal_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Deal_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Deal_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Deal_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `Reservation`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Deal_agentId_fkey` FOREIGN KEY (`agentId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Deal_propertyLeaseId_fkey` FOREIGN KEY (`propertyLeaseId`) REFERENCES `PropertyLease`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PropertyExpense` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NOT NULL,
  `providerContactId` VARCHAR(191) NULL,
  `ownerContactId` VARCHAR(191) NULL,
  `category` VARCHAR(80) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `dueDate` DATE NULL,
  `paidAt` DATETIME(3) NULL,
  `status` ENUM('PENDING','PAID','CANCELED') NOT NULL DEFAULT 'PENDING',
  `chargeToRenter` BOOLEAN NOT NULL DEFAULT false,
  `chargeToOwner` BOOLEAN NOT NULL DEFAULT true,
  `documentUrl` VARCHAR(500) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `PropertyExpense_tenantId_status_dueDate_idx` (`tenantId`,`status`,`dueDate`),
  INDEX `PropertyExpense_propertyId_idx` (`propertyId`),
  INDEX `PropertyExpense_providerContactId_idx` (`providerContactId`),
  INDEX `PropertyExpense_ownerContactId_idx` (`ownerContactId`),
  CONSTRAINT `PropertyExpense_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PropertyExpense_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `PropertyExpense_providerContactId_fkey` FOREIGN KEY (`providerContactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `PropertyExpense_ownerContactId_fkey` FOREIGN KEY (`ownerContactId`) REFERENCES `Contact`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `OwnerSettlement` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `ownerContactId` VARCHAR(191) NOT NULL,
  `periodStart` DATE NOT NULL,
  `periodEnd` DATE NOT NULL,
  `grossCollected` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `expensesTotal` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `commissionTotal` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `taxesTotal` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `netAmount` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `status` ENUM('DRAFT','READY','PAID','CANCELED') NOT NULL DEFAULT 'DRAFT',
  `paidAt` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `OwnerSettlement_tenantId_status_idx` (`tenantId`,`status`),
  INDEX `OwnerSettlement_tenantId_periodStart_periodEnd_idx` (`tenantId`,`periodStart`,`periodEnd`),
  INDEX `OwnerSettlement_ownerContactId_idx` (`ownerContactId`),
  CONSTRAINT `OwnerSettlement_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `OwnerSettlement_ownerContactId_fkey` FOREIGN KEY (`ownerContactId`) REFERENCES `Contact`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `OwnerSettlementLine` (
  `id` VARCHAR(191) NOT NULL,
  `settlementId` VARCHAR(191) NOT NULL,
  `propertyId` VARCHAR(191) NULL,
  `type` VARCHAR(60) NOT NULL,
  `sourceType` VARCHAR(60) NULL,
  `sourceId` VARCHAR(80) NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `OwnerSettlementLine_settlementId_idx` (`settlementId`),
  INDEX `OwnerSettlementLine_propertyId_idx` (`propertyId`),
  CONSTRAINT `OwnerSettlementLine_settlementId_fkey` FOREIGN KEY (`settlementId`) REFERENCES `OwnerSettlement`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `OwnerSettlementLine_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `RecurringCharge` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `propertyLeaseId` VARCHAR(191) NOT NULL,
  `type` ENUM('ALQUILER','EXPENSAS','DEPOSITO','LUZ','GAS','AGUA','SEGURO','IMPUESTO','PENALIDAD','INTERES','NOTA_DEBITO','NOTA_CREDITO','OTROS') NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(12,2) NULL,
  `percentage` DECIMAL(6,2) NULL,
  `frequencyMonths` INTEGER NOT NULL DEFAULT 1,
  `dueDay` INTEGER NOT NULL DEFAULT 10,
  `startsAt` DATE NOT NULL,
  `endsAt` DATE NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RecurringCharge_tenantId_active_idx` (`tenantId`,`active`),
  INDEX `RecurringCharge_propertyLeaseId_active_idx` (`propertyLeaseId`,`active`),
  CONSTRAINT `RecurringCharge_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `RecurringCharge_propertyLeaseId_fkey` FOREIGN KEY (`propertyLeaseId`) REFERENCES `PropertyLease`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;